theme: jekyll-theme-architect

# Name of your site (displayed in the header)
name: David Betteridge
title: David Betteridge

# Short bio or description (displayed in the header)
description: Co-founder of York Developers.  Ultra Runner.  Works at Hivemap Ltd

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/8648315?v=3&s=400

markdown: kramdown

permalink: /blog/:year/:month/:day/:title